# Generated by Django 4.1 on 2022-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('state', models.IntegerField()),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('total_prec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.IntegerField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('rain_depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
